export const FETCH_VIEW  = 'FETCH_VIEW'
export const FETCH_VIEW_SUCCESS = "FETCH_VIEW_SUCCESS"
export const FETCH_VIEW_FAILED = "FETCH_VIEW_FAILED"

export const UPDATE_COUNT_SUCCESS = 'UPDATE_COUNT_SUCCESS'
export const UPDATE_COUNT_FAILED = 'UPDATE_COUNT_FAILED'